### ISSUE TITLE
dockerise the service

### ISSUE THREAD

**Issue by simonjupp** [EBISPOT/gwas-template-services#4]
Provide a docker file that builds and runs the template service. Suggest to build from the `python:3-alpine` base image.

**Comment by DSuveges** [comment]
OK, this issue is not as easy as I was hoping for: as the development is done on OSX, the environment file is full with OSX specific packages that are not able to install on a Linux based container. See this SO thread: [link](https://stackoverflow.com/questions/53819954/cant-recreate-conda-environment-in-docker)

What I am going to do now is to build a functional environment on linux, and try to use that as source.

**Comment by DSuveges** [comment]
OK, The the application has now a dockerfile, giving instructions on how to build a docker image an start up a container. #16
